### ISSUE TITLE
可以在线安装别的模型和lora吗

### ISSUE THREAD

**Issue by feixiaomi** [KKGo1999/Stable-diffusion-person#2]
找了找没找到，在colab只能自己上传吗。。

**Comment by KKGo1999** [comment]
可以的，可以参考 Repo里第二个colab 链接，那个就是利用了LoRA的

**Comment by KKGo1999** [comment]
如果你要安装别的模型，也可以参考第3个colab 的链接

**Comment by feixiaomi** [comment]
> 如果你要安装别的模型，也可以参考第3个colab 的链接

收到，谢谢🤝
